version: "3.8"

services:
  postgres:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=green_bay
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    build:
      context: ./Backend/src
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=green_bay;Username=postgres;Password=postgres
      - JwtSettings__Key=DfRVw5b0ahmA2fPYRScOj2uvPDEiokpu3MxBLRnw
    depends_on:
      - postgres
